import { CelestialBody } from "./celestial-body";
import { OrbitingCelestialBody } from "./orbiting-celestial-body";
declare const kerbol: CelestialBody;
declare const moho: OrbitingCelestialBody;
declare const eve: OrbitingCelestialBody;
declare const gilly: OrbitingCelestialBody;
declare const kerbin: OrbitingCelestialBody;
declare const mun: OrbitingCelestialBody;
declare const minmus: OrbitingCelestialBody;
declare const duna: OrbitingCelestialBody;
declare const ike: OrbitingCelestialBody;
declare const dres: OrbitingCelestialBody;
declare const jool: OrbitingCelestialBody;
declare const laythe: OrbitingCelestialBody;
declare const vall: OrbitingCelestialBody;
declare const tylo: OrbitingCelestialBody;
declare const bop: OrbitingCelestialBody;
declare const pol: OrbitingCelestialBody;
declare const eeloo: OrbitingCelestialBody;
export { kerbol, moho, eve, gilly, kerbin, mun, minmus, duna, ike, dres, jool, laythe, vall, tylo, bop, pol, eeloo };
